-- MUTI Database Schema
-- Initial schema for MUTI (MUsic Type Indicator)

-- Survey 테이블
CREATE TABLE surveys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Question 테이블
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    axis VARCHAR(10) NOT NULL,
    order_index INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (survey_id) REFERENCES surveys(id) ON DELETE CASCADE,
    CONSTRAINT chk_axis CHECK (axis IN ('E_I', 'S_F', 'A_D', 'P_U'))
);

-- QuestionOption 테이블
CREATE TABLE question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    content VARCHAR(500) NOT NULL,
    direction VARCHAR(1) NOT NULL,
    score INT NOT NULL,
    order_index INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
    CONSTRAINT chk_direction CHECK (direction IN ('E', 'I', 'S', 'F', 'A', 'D', 'P', 'U')),
    CONSTRAINT chk_score CHECK (score BETWEEN 1 AND 5)
);

-- SurveyResult 테이블
CREATE TABLE survey_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id BIGINT NOT NULL,
    muti_type VARCHAR(4) NOT NULL,
    ei_score INT NOT NULL,
    sf_score INT NOT NULL,
    ad_score INT NOT NULL,
    pu_score INT NOT NULL,
    session_id VARCHAR(255),
    user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (survey_id) REFERENCES surveys(id) ON DELETE CASCADE,
    CONSTRAINT chk_muti_type CHECK (muti_type IN (
        'ESAP', 'ESAU', 'ESDP', 'ESDU',
        'EFAP', 'EFAU', 'EFDP', 'EFDU',
        'ISAP', 'ISAU', 'ISDP', 'ISDU',
        'IFAP', 'IFAU', 'IFDP', 'IFDU'
    ))
);

-- SurveyResponse 테이블
CREATE TABLE survey_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_result_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    question_option_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (survey_result_id) REFERENCES survey_results(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id),
    FOREIGN KEY (question_option_id) REFERENCES question_options(id)
);

-- 인덱스 생성
CREATE INDEX idx_surveys_active ON surveys(active);
CREATE INDEX idx_questions_survey_id ON questions(survey_id);
CREATE INDEX idx_questions_axis ON questions(axis);
CREATE INDEX idx_question_options_question_id ON question_options(question_id);
CREATE INDEX idx_survey_results_survey_id ON survey_results(survey_id);
CREATE INDEX idx_survey_results_muti_type ON survey_results(muti_type);
CREATE INDEX idx_survey_results_session_id ON survey_results(session_id);
CREATE INDEX idx_survey_results_user_id ON survey_results(user_id);
CREATE INDEX idx_survey_responses_result_id ON survey_responses(survey_result_id);